namespace: hetzner
name: hcloud
version: 5.3.1
readme: README.md
authors:
  - Hetzner Cloud (github.com/hetznercloud)
description: A Collection for managing Hetzner Cloud resources
license:
  - GPL-3.0-or-later
tags:
  - hetzner
  - cloud
  - hcloud
repository: https://github.com/ansible-collections/hetzner.hcloud
documentation: https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud
homepage: https://github.com/ansible-collections/hetzner.hcloud
issues: https://github.com/ansible-collections/hetzner.hcloud/issues
