namespace: hetzner
name: hcloud
version: 1.2.1
readme: README.md
authors:
  - Hetzner Cloud (github.com/hetznercloud)
description: A Collection for managing Hetzner Cloud resources
license: GPL-3.0-or-later
tags:
  - hetzner
  - cloud
  - hcloud
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: https://github.com/ansible-collections/hetzner.hcloud
documentation: https://github.com/ansible-collections/hetzner.hcloud/tree/master/docs
homepage: https://github.com/ansible-collections/hetzner.hcloud
issues: https://github.com/ansible-collections/hetzner.hcloud/issues
